<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'scielopreprint' => '/ScieloPreprint.inc.php',
                'scielosubmission' => '/ScieloSubmission.inc.php',
                'scielosubmissionsojsreport' => '/ScieloSubmissionsOJSReport.inc.php',
                'scielosubmissionsopsreport' => '/ScieloSubmissionsOPSReport.inc.php',
                'scielosubmissionsreport' => '/ScieloSubmissionsReport.inc.php',
                'submissionauthor' => '/SubmissionAuthor.inc.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
